dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink@1.5.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@chainlink=smartcontractkit/chainlink@1.5.0"

dotenv: .env
networks:
  development:
    verify: False
  ganache:
    verify: False
  kovan:
    verify: True
    weth_token: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
    fau_token: "0xfab46e002bbf0b4509813474841e0716e6730136"
    dai_usd_price_feed: "0x777A68032a88E5A84678A77Af2CD65A7b3c0775a"
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"

wallets:
  from_key: "0xbd8db5f907fdf556fe307cae37648d0d6a1421647b96b1820d835de3b791bb9b"
